# Generated by Django 6.0.4 on 2026-04-12 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrona', '0002_guestbookentry_profile_bio_moodpulse_usernote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='InspirationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inspiration/%Y/%m/')),
                ('external_image_url', models.URLField(blank=True, max_length=500)),
                ('author_display_override', models.CharField(blank=True, help_text='Подпись автора для демо-постов (иначе — имя из профиля)', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
