# Generated by Django 6.0.4 on 2026-04-12 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrona', '0003_profile_avatar_and_inspiration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysnapshot',
            name='integration_ref',
            field=models.CharField(blank=True, help_text='ПР-08: метка записи DailyIndex для выгрузки в CRM', max_length=120),
        ),
        migrations.AddField(
            model_name='inspirationpost',
            name='title',
            field=models.CharField(blank=True, help_text='ПР-03 InspirationPost.title', max_length=200),
        ),
        migrations.AddField(
            model_name='moment',
            name='integration_ref',
            field=models.CharField(blank=True, help_text='ПР-08: внешний ключ/метка для синхронизации с CRM (webhook)', max_length=120),
        ),
        migrations.AddField(
            model_name='moment',
            name='location',
            field=models.CharField(blank=True, help_text='ПР-03 Moment.location — место, если указано', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='ПР-03 User.age — опционально', null=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='ПР-03: дни недели, напр. mon,wed,fri', max_length=64),
        ),
        migrations.CreateModel(
            name='AdaptedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_action', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('skipped', 'skipped'), ('later', 'later')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspiration_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapted_actions', to='chrona.inspirationpost')),
                ('micro_intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapted_actions', to='chrona.microintervention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapted_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
