# Generated by Django 6.0.4 on 2026-04-12 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chrona', '0004_pr02_pr03_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='moments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='dailysnapshot',
            name='integration_ref',
            field=models.CharField(blank=True, help_text='Необязательная метка для внешних систем', max_length=120),
        ),
        migrations.AlterField(
            model_name='inspirationpost',
            name='title',
            field=models.CharField(blank=True, help_text='Короткий заголовок', max_length=200),
        ),
        migrations.AlterField(
            model_name='moment',
            name='emotion',
            field=models.CharField(choices=[('calm', 'calm'), ('warm', 'warm'), ('growth', 'growth'), ('deep', 'deep'), ('joy', 'joy'), ('gratitude', 'gratitude'), ('tired', 'tired'), ('anxious', 'anxious'), ('hope', 'hope'), ('tender', 'tender'), ('focus', 'focus'), ('light', 'light')], default='calm', max_length=16),
        ),
        migrations.AlterField(
            model_name='moment',
            name='integration_ref',
            field=models.CharField(blank=True, help_text='Необязательная метка для внешних систем', max_length=120),
        ),
        migrations.AlterField(
            model_name='moment',
            name='location',
            field=models.CharField(blank=True, help_text='Свободное уточнение места (адрес, комната…)', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Необязательно', null=True),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='Дни недели, напр. mon,wed,fri', max_length=64),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrona_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='moment',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='moments', to='chrona.place'),
        ),
    ]
